version: "3.9"
services:
  web:
    build: .
    # image: studentapp_web:latest

    command: "npm run start"

    ports:
      - "3000:3000"

    env_file:
      - ./.env

    # volumes:
    #   - /home/ubuntu/SERVER/Prod/SkillslashMain:/app
