# FROM mhart/alpine-node:14 AS builder
FROM node:14

RUN mkdir /app

WORKDIR /app
# COPY package.json /app
# COPY package-lock.json /app
COPY . /app
RUN npm install
COPY . /app
RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "start"]

