export const hPartner = [
  {
    id: 1,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Google.webp",
    cWidth: "150",
    cHeight: "30",
    mWidth: "70",
    mHeight: "30",
    fs: "false",
  },
  {
    id: 2,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Amazon.png",
    cWidth: "120",
    cHeight: "40",
    mWidth: "124",
    mHeight: "50",
    fs: "false",
  },
  {
    id: 3,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Microsoft.png",
    cWidth: "150",
    cHeight: "40",
    mWidth: "120",
    mHeight: "40",
    fs: "false",
  },
  {
    id: 4,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Flipkart.png",
    cWidth: "100",
    cHeight: "40",
    mWidth: "100",
    mHeight: "40",
    fs: "false",
  },
  {
    id: 5,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/facebook.png",
    cWidth: "150",
    cHeight: "40",
    mWidth: "120",
    mHeight: "40",
    fs: "false",
  },
  {
    id: 6,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/TCS.png",
    cWidth: "120",
    cHeight: "40",
    mWidth: "120",
    mHeight: "40",
    fs: "true",
  },
  {
    id: 7,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/PAYTM_logo.png",
    cWidth: "140",
    cHeight: "44",
    mWidth: "140",
    mHeight: "44",
    fs: "true",
  },
  {
    id: 8,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Zoho.png",
    cWidth: "140",
    cHeight: "48",
    mWidth: "140",
    mHeight: "48",
    fs: "true",
  },
];
export const pPartner = [
  {
    id: 1,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/liquiloans.webp",
    cWidth: "300",
    cHeight: "120",
    mWidth: "90",
    mHeight: "40",
    fs: "false",
  },
  {
    id: 2,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/propelld.webp",
    cWidth: "500",
    cHeight: "200",
    mWidth: "120",
    mHeight: "40",
    fs: "false",
  },
  {
    id: 3,
    img: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/zest-logo.webp",
    cWidth: "200",
    cHeight: "58",
    mWidth: "80",
    mHeight: "20",
    fs: "false",
  },
];
