export const fsTrainer = [
  {
    id: 1,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/SinghSanket.webp",
    pWidth: "270",
    pHeight: "258",
    name: "Sanket Singh",
    alt: "best full stack course review by sanket-singh",
    position: "Software Engineer II",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/GoogleM.webp",
    cWidth: "83",
    cHeight: "30",
    mImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/GoogleM.webp",
    mWidth: "83",
    mHeight: "30",
  },
  {
    id: 2,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/Goel.webp",
    pWidth: "270",
    pHeight: "258",
    name: "Chirag Goel",
    alt: "best full stack  developer course online review by sanket-singh",
    position: "Sr. Software Engineer",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/Microsoft-new.png",
    cWidth: "100",
    cHeight: "30",
    mImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/Microsoft-new.png",
    mWidth: "100",
    mHeight: "30",
  },
  {
    id: 3,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/KumarAmit.webp",
    pWidth: "271",
    pHeight: "258",
    alt: "popular full stack developer course review by sanket-singh",
    name: "Amit Kumar",
    position: "Software Engineer",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/Microsoft-new.png",
    cWidth: "100",
    cHeight: "30",
    mImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/Microsoft-new.png",
    mWidth: "100",
    mHeight: "30",
  },
  {
    id: 5,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/DaveDhawal.webp",
    pWidth: "271",
    pHeight: "258",
    name: "Dhaval Dave",
    alt: "Best full stack trainer from walmart",
    position: "Staff Software Engineer",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/image%2B230.png",
    cWidth: "112",
    cHeight: "32",
    mImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/image%2B230.png",
    mWidth: "112",
    mHeight: "32",
  },
  {
    id: 6,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/AmanA.webp",
    pWidth: "271",
    pHeight: "258",
    name: "Aman Garg",
    alt: "Aman garg a full stack developer trainer in  skillslash",
    position: "Software Engineer II",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    cWidth: "90",
    cHeight: "27",
    mImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/amazon.png",
    mWidth: "90",
    mHeight: "27",
  },
  {
    id: 7,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/Naveen.webp",
    pWidth: "271",
    pHeight: "258",
    alt: "learn form full stack alumni naveen yadav",
    name: "Naveen Yadav",
    position: "Software Engineer II",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/PngItem_7189867%2B1.png",
    cWidth: "110",
    cHeight: "24",
    mImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/PngItem_7189867%2B1.png",
    mWidth: "110",
    mHeight: "14",
  },
  {
    id: 8,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/SoumNag.webp",
    pWidth: "271",
    pHeight: "258",
    alt: "soumya",
    name: "Soumya S.",
    position: "Sr. Software Engineer",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/paypal-de.png",
    cWidth: "110",
    cHeight: "31",
    mImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/paypal-de.png",
    mWidth: "110",
    mHeight: "31",
  },
];
export const dsTrainer = [
  {
    id: 1,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/Prathap-ds-desktop.webp",
    pWidth: "262",
    pHeight: "257",
    alt: "data science trainer prathap",
    name: "Prathap B",
    position: "Lead Data Scientist",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/mercedez-inline-logo.png",
    cWidth: "110",
    cHeight: "28",
    mImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/mercedez-ixon.png",
    mWidth: "20",
    mHeight: "20",
  },
  {
    id: 2,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/deepak-kumar-singh.webp",
    pWidth: "262",
    pHeight: "257",
    alt: "data science trainer working in MNC",
    name: "Deepak Singh",
    position: "Senior Data Scientist",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/inmobi-icon.png",
    cWidth: "90",
    cHeight: "21",
    mImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/inmobi-icon.png",
    mWidth: "60",
    mHeight: "29",
  },
  {
    id: 3,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/rohan-aher-desktop.webp",
    pWidth: "262",
    pHeight: "257",
    name: "Rohan Aher",
    alt: "get trained from best trainer of Data science Rohan aher",
    position: "Assistant Manager",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/KPMG-icon.png",
    cWidth: "70",
    cHeight: "29",
    mImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/KPMG-icon.png",
    mWidth: "49",
    mHeight: "20",
  },
  {
    id: 4,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/Lekha-Janardhan-logo-big.webp",
    pWidth: "262",
    pHeight: "257",
    name: "Lekha Janardhan",
    alt: "Lekha janardhan a data scientist giving training ion skillslash",
    position: "Data Scientist",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/analyticedge-logo-big.webp",
    cWidth: "109",
    cHeight: "30",
    mImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/analyticedge-logo-big.webp",
    mWidth: "53",
    mHeight: "17",
  },
  {
    id: 5,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/aravind-reddy.webp",
    pWidth: "262",
    pHeight: "257",
    alt: "arvind reddy",
    name: "Aravind Reddy",
    position: "Senior Data Scientist",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/maytronics-logo-big.webp",
    cWidth: "105",
    cHeight: "30",
    mImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/maytronics-logo.webp",
    mWidth: "78",
    mHeight: "16",
  },
  {
    id: 6,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/Parikshit.webp",
    pWidth: "262",
    pHeight: "257",
    alt: "Pariskhit",
    name: "Parikshit Sohoni",
    position: "Co-founder",
    mImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/Glovatrix-icon.webp",
    cWidth: "150",
    cHeight: "30",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/Glovatrix-icon-big.webp",
    mWidth: "80",
    mHeight: "21",
  },
  {
    id: 7,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/ajay-kumar-gupta.webp",
    pWidth: "262",
    pHeight: "257",
    alt: "Ajay Kumar Gupta",
    name: "Ajay Gupta",
    position: "R&D Engineer",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/synopsis-logo.webp",
    cWidth: "99",
    cHeight: "29",
    mImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/synopsis-logo.webp",
    mWidth: "80",
    mHeight: "21",
  },
];
