export const FsAlumni = [
  {
    id: 1,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/GIRISH_BALLAMPALLI.webp",
    pWidth: "85",
    pHeight: "85",
    position: "Software Developer",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/tessellation-logo.webp",
    cWidth: "30",
    cHeight: "30",
  },
  {
    id: 2,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Ankur_Singh.webp",
    pWidth: "85",
    pHeight: "85",
    position: "Software Engineer",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/Nike-s.webp",
    cWidth: "95",
    cHeight: "27",
  },
  {
    id: 3,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Anurag_Sinha.webp",
    pWidth: "85",
    pHeight: "85",
    position: "Software Engineer",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/pega-logo.webp",
    cWidth: "100",
    cHeight: "27",
  },
  {
    id: 4,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Muralikrishna_Alichetty.webp",
    pWidth: "85",
    pHeight: "85",
    position: "Database Consultant",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/itician.webp",
    cWidth: "100",
    cHeight: "28",
  },
];
export const webAlumni = [
  {
    id: 1,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Muralikrishna_Alichetty.webp",
    pWidth: "85",
    pHeight: "85",
    position: "Database Consultant",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/itician.webp",
    cWidth: "100",
    cHeight: "28",
  },
  {
    id: 2,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/suresh-kumar-alumi-web.webp",
    pWidth: "85",
    pHeight: "85",
    position: "Dot Net Developer",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/infinte.webp",
    cWidth: "50",
    cHeight: "49",
  },
  {
    id: 3,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/Manisha_singh.webp",
    pWidth: "85",
    pHeight: "85",
    position: "Sr. Software Engineer",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/tcs-lgo.webp",
    cWidth: "90",
    cHeight: "36",
  },
  {
    id: 4,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/PANKAJ_CHOWDHURY.webp",
    pWidth: "85",
    pHeight: "85",
    position: "Senior Analyst",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/IBM.webp",
    cWidth: "80",
    cHeight: "32",
  },
];
export const dsAlumni = [
  {
    id: 1,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/akarsh-srivastava-big.webp",
    pWidth: "85",
    pHeight: "85",
    position: "Data Analyst",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/trueblue-big.webp",
    cWidth: "135",
    cHeight: "38",
  },
  {
    id: 2,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/rishabh-jaiswal-icon-big.webp",
    pWidth: "85",
    pHeight: "85",
    position: "Credit Risk Analyst",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/dvara.webp",
    cWidth: "80",
    cHeight: "58",
  },
  {
    id: 3,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/Madhuparana.webp",
    pWidth: "85",
    pHeight: "85",
    position: "Data Scientist",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/tech-mahindra-big.webp",
    cWidth: "130",
    cHeight: "38",
  },
  {
    id: 4,
    pImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/pragyan-prakash-big.webp",
    pWidth: "85",
    pHeight: "85",
    position: "Data Scientist",
    cImg: "https://skillslash-cdn.s3.ap-south-1.amazonaws.com/static/web/New-UI/Accenture-big.webp",
    cWidth: "130",
    cHeight: "39",
  },
];
